version: "3.4"

networks:
  apps:
    external: true

services:
  app:
    image: node:12.18-alpine
    container_name: app
    restart: "always"
    tty: true
    ports:
      - "$FRONTEND_PORT:8090"
    volumes:
      - ./docker/front-end/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./app:/var/dev/
      - ./docker/front-end/locks:/root/locks
    networks:
      - apps
    command: 'npm run serve'
    working_dir: /var/dev
    labels:
      - "traefik.http.routers.app.rule=Host(`vue.raisbbs.com.br`)"
      - "traefik.docker.network=apps"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:vue.raisbbs.com.br"
