version: '3'
services:
 vue-ui:
    build:
      context: ./app
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./my-app:/usr/src/app/app
       - /usr/src/app/app/node_modules