FROM debian:buster-slim

RUN \
# adicionar repo PHP 
    apt update -y && \
    apt install -y wget lsb-release apt-transport-https ca-certificates && \
    wget https://packages.sury.org/php/apt.gpg \
        -O /etc/apt/trusted.gpg.d/php.gpg && \
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list ; \
# instalar PHP e dependências
    apt update -y  && \
    apt install -y php7.4-fpm composer \
        php7.4-mbstring php7.4-xml php7.4-json php7.4-mysql \
        php7.4-curl php7.4-zip php7.4-bcmath php8.0-gd \
        php-xdebug iputils-ping

EXPOSE 9000